export const COMPANY_IS_ADDED = "تم اضافة الشركة بنجاح";
export const COMPANY_IS_UPDATED = "تم تعديل بيانات الشركة بنجاح";
export const COMPANY_IS_DELETED = "تم حذف الشركة بنجاح";
export const INVOICE_IS_ADDED = "تم إرسال الفاتورة الي العميل بنجاح";
export const INVOICE_IS_DELETED = "تم حذف الفاتورة بنجاح";
export const CV_IS_SENDED_waiting =
  "أنتظر حتي اختفاء هذا الاشعار قبل الارسال ثانيا";
export const CV_IS_SENDED = "تم إرسال السيرة الذاتية الي هذه الدفعة بنجاح";
export const CV_IS_SENDED_COMPLETED =
  "تم إرسال السيرة الذاتية الي كل الايميلات بنجاح";
